from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field

class CoverageGap(BaseModel):
    """Represents a gap between product requirements and the generated test plan."""
    description: str = Field(description="Description of the missing flow or edge case")
    severity: str = Field(description="Severity of the gap: High, Medium, Low")

class TestScript(BaseModel):
    """Represents an executable Playwright test script generated by the system."""
    filename: str = Field(description="Name of the generated test file, e.g., login.spec.ts")
    code: str = Field(description="The executable Playwright test code")

class TestFailure(BaseModel):
    """Represents a failure encountered during test execution."""
    filename: str = Field(description="File that failed")
    error_message: str = Field(description="The raw error message from the test runner")
    is_script_defect: bool = Field(description="True if it's a broken locator/script, False if it's a genuine app bug")
    healer_action_taken: Optional[str] = Field(description="What the healer did to try and fix it", default=None)

class AgentState(BaseModel):
    """
    Defines the main state object for the LangGraph orchestration.
    Maintains the state across planning, generation, execution, and healing phases.
    """
    # Inputs
    url: str = Field(description="The target web application URL", default="")
    prd_context: Optional[str] = Field(description="Optional product requirements context", default=None)
    dom_context: Optional[str] = Field(description="Optional snapshot of the page DOM", default=None)
    test_data: Dict[str, Any] = Field(description="Provided test credentials and states for exploration", default_factory=dict)
    
    # Planner outputs
    test_plan: Optional[str] = Field(description="The human-readable test plan", default=None)
    planner_attempts: int = Field(description="Number of times the Planner has run", default=0)
    
    # Meta-Agent outputs (Evaluation)
    coverage_gaps: List[CoverageGap] = Field(description="Identified coverage gaps", default_factory=list)
    
    # Generator outputs
    test_scripts: List[TestScript] = Field(description="Generated executable scripts", default_factory=list)
    
    # Execution outputs (from MCP)
    execution_results: Dict[str, Any] = Field(description="Raw execution results from the test runner", default_factory=dict)
    test_failures: List[TestFailure] = Field(description="List of parsed test failures", default_factory=list)
    
    # Healer outputs
    healer_attempts: int = Field(description="Number of times the healer has attempted fixes", default=0)
    
    # Final output
    final_report: Optional[str] = Field(description="The synthesized final test quality report", default=None)
